services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
    env_file:
    - .env
    ports:
    - 8000:8000
    volumes:
    - .:/home/app

  db:
    image: mongo:6.0
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data:
