services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      db-init:
        condition: service_completed_successfully
    env_file:
    - .env
    networks:
    - default
    ports:
    - 8000:8000
    volumes:
    - .:/home/app

  db:
    build:
      context: ./deploy/mongodb/
      dockerfile: ./Dockerfile
    container_name: db
    networks:
    - default
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db

  db-init:
    build:
      context: ./deploy/mongodb-init/
      dockerfile: ./Dockerfile
    container_name: db-init
    depends_on:
      db:
        condition: service_started
    env_file:
    - ./deploy/mongodb-init/.env
    networks:
    - default

  dlq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dlq
    command: python src/infrastructure/ports/dlq/main.py
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
        restart: true
    env_file:
    - .env
    networks:
    - default
    volumes:
    - .:/home/app

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    command: python src/infrastructure/ports/publisher/main.py
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
        restart: true
    env_file:
    - .env
    networks:
    - default
    volumes:
    - .:/home/app

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscriber
    command: python src/infrastructure/ports/subscriber/main.py
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
        restart: true
      slack:
        condition: service_healthy
        restart: true
      smtp:
        condition: service_healthy
        restart: true
    env_file:
    - .env
    networks:
    - default
    volumes:
    - .:/home/app

  rabbitmq:
    build:
      context: ./deploy/rabbitmq/
      dockerfile: ./Dockerfile
    container_name: rabbitmq
    healthcheck:
      test: [CMD, /etc/rabbitmq/healthcheck.sh]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - default
    ports:
    - 5672:5672
    - 15672:15672

  slack:
    container_name: slack
    build:
      context: ./deploy/slack/
      dockerfile: ./Dockerfile
    healthcheck:
      test: [CMD-SHELL, /home/wiremock/healthcheck.sh]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - default
    ports:
    - 8080:8080
    - 8443:8443

  smtp:
    build:
      context: ./deploy/smtp/
      dockerfile: ./Dockerfile
    container_name: smtp
    env_file:
    - ./deploy/smtp/.env
    healthcheck:
      test: [CMD-SHELL, /home/smtp4dev/healthcheck.sh]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - default
    ports:
    - 8180:80

volumes:
  mongo-data:

networks:
  default:
    name: backend-challenge-network
