from uuid import UUID

from pydantic import BaseModel, Field

from src.domain.entities import AssistanceRequest as Assistance
from src.domain.value_objects import Status, Topic


class AssistanceRequest(BaseModel):
    id: UUID = Field(
        title="Request ID.",
        description="Request ID generated by the system.",
        examples=["649757dcee7d6681992a9c22"],
    )
    topic: Topic = Field(
        title="Topic name", description="Topic related to the assistance request.", examples=["sales", "pricing"]
    )
    description: str = Field(
        title="Assistance request description",
        description="Assistance request detail provided by the requester bot.",
        max_length=300,
        examples=["We need some details about the product #REF00123654"],
    )
    status: Status = Field(
        title="Request status",
        description="Indicates the current status of the request.",
        examples=["pending", "succeeded", "failed"],
    )

    @staticmethod
    def from_entity(assistance_request: Assistance) -> "AssistanceRequest":
        return AssistanceRequest(
            id=assistance_request.id,
            topic=assistance_request.topic,
            description=assistance_request.description,
            status=assistance_request.status,
        )
